### ISSUE TITLE
Do you have a demo video focus on audio?

### ISSUE THREAD

**Issue by NoFish-528** [MingLunHan/X-LLM-Speech#1]
Thanks for your amazing work, do you have a demo audio about this paper?

**Comment by MingLunHan** [comment]
Hello!

The final X-LLM model based on ChatGLM has the ability to accept speech input and directly answer questions in an end-to-end manner, rather than in a cascading manner. In our internal testing, the user experience is good. However, there are many factors that currently prevent us from having enough energy and time to fully improve the related open source content. My main responsibility is to implement and support the basic capabilities of the speech component. We have recently been handling graduation-related affairs, and there is a lot of internal work that needs to be handed over and processed. If you urgently need related code support, you can refer to my other repository, which contains the core code of the CIF mechanism required in the X-LLM paper. I am currently standardizing and organizing the code related to the speech basic capabilities of X-LLM, and planning to upload it to GitHub as soon as possible. Regarding the issue of DEMO, you can still ask questions in the original X-LLM repository. This repository is mainly responsible for implementing the speech basic capabilities, not the entire system.

Thank you for your attention and understanding!

**Comment by NoFish-528** [comment]
Ok, thank you for your explanation. congratulations to your graduation !

**Comment by MingLunHan** [comment]
@NoFish-528 Thanks!
